const TEXT_FIELD_ON_CLICK = "TEXT_FIELD_ON_CLICK";
const TEXT_FIELD_ON_CHANGE = "TEXT_FIELD_ON_CHANGE";
const TEXT_FIELD_ON_BLUR = "TEXT_FIELD_ON_BLUR";
const TEXT_FIELD_ON_FOCUS = "TEXT_FIELD_ON_FOCUS";

export {
  TEXT_FIELD_ON_CLICK,
  TEXT_FIELD_ON_CHANGE,
  TEXT_FIELD_ON_BLUR,
  TEXT_FIELD_ON_FOCUS,
};
